#server:
#  port: 10001
#spring:
#  sleuth:
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    discovery-client-enabled: false
#
#  application:
#    name: server-gateway
#  main:
#    allow-bean-definition-overriding: true
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowCredentials: true
#            allowedHeaders: "*"
#      #开启网关对nacos
#      discovery:
#        locator:
#          enabled: true
#          route-id-prefix: gateway-
#    #配置nacos
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        port: 7777
#        dashboard: 127.0.0.1:8888
#      web-context-unify: false
#      eager: true
#
#        #routes:
#        #  - id: user-gateway
#        #uri: http://localhost:8060
#        #    uri: lb://server-user
#        #    order: 1
#        #    predicates:
#        #      - Path=/server-user/**
#        #   filters:
#        #   - StripPrefix=1
#
#        #  - id: product-gateway
#        #uri: http://localhost:8070
#        #  uri: lb://server-product
#        #  order: 1
#        #  predicates:
#        #    - Path=/server-product/**
#        # filters:
#        #   - StripPrefix=1
#
#        #- id: order-gateway
#        #uri: http://localhost:8080
#        #从nacos中获取服务
#        #  uri: lb://server-order
#        #  order: 1
#        # predicates:
#        #   - Path=/server-order/**
#        # filters:
#      #   - StripPrefix=1